### ISSUE TITLE
500 Internal Server Error for Service 1511

### ISSUE THREAD

**Issue by Rascalitoes** [tosdr/edit.tosdr.org#1059]
**Bug Description:**
Received 500 Internal Server Error on [https://edit.tosdr.org/services/1511/annotate](https://edit.tosdr.org/services/1511/annotate)

**Expected behavior:**
I was expecting to be brought to the Shopify TOU annotation page.

**Response Headers**
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Sat, 03 Apr 2021 23:01:37 GMT
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
X-Request-Id: 719d633c-ffb7-4ea6-9d3f-6c7ed1ff0fe0
X-Runtime: 0.771214
Vary: Accept-Encoding
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transfer-Encoding: chunked
Via: 1.1 vegur

**Desktop**
Firefox 87.0 (64-bit)

**Additional Context**
I've tried accessing this page at a few different times and always received this error

**Comment by JustinBack** [comment]
Sadly this is a known issue (#974) and has to be manually fixed.


I've gone ahead and fixed the service.

**Comment by Rascalitoes** [comment]
That's unfortunate that it's a known issue
Thank you for fixing this instance though!
