### ISSUE TITLE
Another 500 Internal Server Error for Service 1511

### ISSUE THREAD

**Issue by Rascalitoes** [tosdr/edit.tosdr.org#1060]
Bug Description:
Received 500 Internal Server Error on https://edit.tosdr.org/services/1511/annotate

Expected behavior:
I was expecting to be brought to the Shopify TOU annotation page.

Response Headers
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Tue, 06 Apr 2021 00:25:39 GMT
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
X-Request-Id: d0eb7044-fe3e-4178-973b-bd598d97b16b
X-Runtime: 0.231857
Vary: Accept-Encoding
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transfer-Encoding: chunked
Via: 1.1 vegur

Desktop
Firefox 87.0 (64-bit)

Additional Context
This is the same thing as error #1059 but it's happened again. Some new files were added recently, so that may be part of the source of the issue?

**Comment by JustinBack** [comment]
I deployed a possible fix in https://github.com/tosdr/edit.tosdr.org/commit/61e31e1e04fa0dac170663951140a813f6f63177

**Comment by JustinBack** [comment]
Seems the fix worked

**Comment by Rascalitoes** [comment]
Yes! Everything's working now. Thank you so much, and sorry for bothering you again.

**Comment by JustinBack** [comment]
All good :-) It was a much needed fix as manually fixing it is tedious by entering the production database
