### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by Haleymiranda79** [tosdr/edit.tosdr.org#1080]
Site tells me to go to settings to log in which you have to be logged in to do.

**Comment by JustinBack** [comment]
On which site were you on exactly as I cannot reproduce it

**Comment by Haleymiranda79** [comment]
https://www.indiegogo.com/accounts/sign_up

**Comment by JustinBack** [comment]
Try contacting indiegogo, this is the wrong place

**Comment by Haleymiranda79** [comment]
I'm so sorry. Been a long day.

**Comment by JustinBack** [comment]
No worries! Strangely enough I can see the register site just fine
