### ISSUE TITLE
Adding documents

### ISSUE THREAD

**Issue by JCBerger** [tosdr/edit.tosdr.org#1085]
At one point, I thought I had the ability to add documents to services, but I can no longer find that option. Was this feature removed, user permissions were changed, or am I just missing how to do it?

**Comment by JustinBack** [comment]
It is only possible for curators to create documents and services. This was done in 4810b2aaa41c379270cba7c3224c36b564a952ec to prevent spam. You can contact me through justin.back@tosdr.org if you'd like to have the curator status, just send me your username on edit.tosdr.org and I'll upgrade your account.
