### ISSUE TITLE
Out of date README.md

### ISSUE THREAD

**Issue by lizzyd710** [tosdr/edit.tosdr.org#1093]
I wanted to get more information on how to contribute to this project, and the README mentions referring to a CONTRIBUTING.md, but there is no file in this repository with that name. After a few minutes I realized this was because CONTRIBUTING.md was renamed to QUICKSTART.md in an earlier commit. 

I know this is small, but changing the README to reflect the new name could quell some potential confusion.

(I wasn't sure if I could make the change myself and submit a PR or not, but I would be happy to do so.)

**Comment by Vinnl** [comment]
Yes absolutely, feel free to send a PR and tag me on it!
