### ISSUE TITLE
Some bad marks are unfairly critical of free/libre/open terms

### ISSUE THREAD

**Issue by wolftune** [tosdr/edit.tosdr.org#1098]
For example https://edit.tosdr.org/points/22685

This might be a poor specific in the terms, but wouldn't this be just the same as Wikipedia or any other thing that is under CC BY-SA or similar free/libre/open terms?

I suggest it's wrong to label a service's terms as bad because it's a wiki and the licensing is FLO.

**Comment by JustinBack** [comment]
I've added your Proposal to our forums, lets move the discussion there :-)

https://tosdr.community/t/some-bad-marks-are-unfairly-critical-of-free-libre-open-terms/2741

**Comment by wolftune** [comment]
https://tosdr.community/ is giving me a 502

**Comment by JustinBack** [comment]
Server did some updates, just as you posted it its back online :-)
