### ISSUE TITLE
Response from the ota server is not parsable JSON

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#1176]
For example, from example.com:
> "{\"fetch\": \"http://example.com\",\"select\": \a"body\"}\"<h1 id=\\\"exampledomain\\\">Example Domain</h1>\\n<p>This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.</p>\\n<p><a href=\\\"https://www.iana.org/domains/example\\\">More information\xE2\x80\xA6</a></p>\""

**Comment by michielbdejong** [comment]
There are two `res.write` statements in server-common.mjs - [line 24](https://github.com/tosdr/ota-engine/blob/0598a949d215a3205cf246c89c7aa3fcb0242784/server-common.mjs#L24) and [line 36](https://github.com/tosdr/ota-engine/blob/0598a949d215a3205cf246c89c7aa3fcb0242784/server-common.mjs#L36).
You can:
* [ ] remove the top one, commit that, push to github,
* [ ]  `ssh root@ota.tosdr.org`,  `su crawler`, `screen -r`, `Crtr-C`, `git pull`, `./prod.sh`, `Ctrl-A Ctrl-D`

**Comment by madoleary** [comment]
I'm confused about how this works. Was I to push the redundant first `res.write` to the branch `tosdr-production`? I pushed to main, and my changes aren't reflected in the `git pull`. Is the image rebuild factored into this workflow?

**Comment by madoleary** [comment]
And what is the correct port for the server? In the code, it says 443. In the `prod.sh` script, it says 4430.

**Comment by michielbdejong** [comment]
> Was I to push the removal of the redundant first res.write to the branch tosdr-production? I pushed to main, and my changes aren't reflected in the git pull.

You can easily check this as follows:
```
root@ota:~# su crawler
crawler@ota:/root$ screen -r
There is no screen to be resumed.
crawler@ota:/root$ screen -ls
No Sockets found in /run/screen/S-crawler.

crawler@ota:/root$ cd
crawler@ota:~$ cd engine/
crawler@ota:~/engine$ git status
On branch tosdr-production
Your branch is up to date with 'origin/tosdr-production'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	declarations
	prod.sh

nothing added to commit but untracked files present (use "git add" to track)
crawler@ota:~/engine$ 
```

> Is the image rebuild factored into this workflow?

no

> And what is the correct port for the server? In the code, it says 443. In the prod.sh script, it says 4430.

4430 is correct, since this script runs as crawler without sudo. Sorry, I think I had that as an uncommitted change on the server, fixed now.
