### ISSUE TITLE
[enh] make more UX-compliant search form

### ISSUE THREAD

**Issue by christalib** [tosdr/edit.tosdr.org#207]
The current search form are basic and do work. However, some use cases are complicated:

* You need to select search to actually make the search
* The reset button is a trick but shouldn't stay there

**Comment by Natouille** [comment]
And make this button available only when a service has been searched (no need to put it on the home page)

**Comment by JesseWeinstein** [comment]
Is this still relevant, and if so, could it be clarified what exactly the proposed change(s) are?

**Comment by Vinnl** [comment]
The interface that this issue was based on no longer exists, so I guess we can close this.
