### ISSUE TITLE
Maybe a legend somewhere to explain the A-F rating

### ISSUE THREAD

**Issue by Natouille** [tosdr/edit.tosdr.org#212]
Why is a service C, D or F ?
Maybe it should be suseful to add a legend or explaination somewhere of how it is rated.

**Comment by JesseWeinstein** [comment]
There is now a legend on https://edit.tosdr.org/about#classification -- does that satisfy this ticket?

**Comment by Vinnl** [comment]
Yeah I guess that's good enough.
