### ISSUE TITLE
search clear button labeled 'back', no 'search' button

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#392]
on https://edit.tosdr.org/services?utf8=%E2%9C%93&query=visible&button= there is no button to search. there is a button to clear the search, labeled 'back'. can this be made clearer to the user?

**Comment by piks3l** [comment]
The "back" allows you to reset and go back to the index, I guess we could make this clearer

**Comment by christalib** [comment]
Closing as it is not relevant anymore
