### ISSUE TITLE
group by service instead of domain

### ISSUE THREAD

**Issue by elypter** [tosdr/edit.tosdr.org#409]
there has been a project that allowed to group all domains of a company together and allowed to show the network of subcompanies. this could be used to avoid dublicatate entries for international and alternative domains.

https://github.com/Jaxkr/Truthbot.org (there is also a chrome extension)

**Comment by michielbdejong** [comment]
Cool! I couldn't find the Chrome extension when searching for 'truthbot', and truthbot.org seems down. The github repo you linked to looks like it contains the Python application but not the database contents. The description of the github repo reads 'Defunct', and I see your issue https://github.com/Jaxkr/Truthbot.org/issues/18 from 2016 - do you think we can revive this project?

In general, we care about the relationship between the domain name you're visiting, and the terms you have to agree to; not so much about who owns the domain. For instance, on yahoo.com you have to agree to the Oath terms on https://policies.oath.com/us/en/oath/terms/otos/index.html

**Comment by elypter** [comment]
the chrome extension can be found here https://github.com/Jaxkr/Truthbot-for-Chrome
there has also been a firefox version in the works but it was never finished or released. i think it is mostly defunct because the hostig has been canceled. with a changed domain and new hosting i think it should be working.

i think this project could help to avoid dublicates for services that have the same tos on different domains like a .com and a .net domain. even if the tos of international domains can be simple they often share as much as possible. it might also be interesting to see how the tos are different in other countries because it shows the tendency the company is going given a certain legal framework. it might also be interesting to link the tos of services of big companies so you can see the average tos score of a company alongside the score of the service you are currently viewing. it is also a good indicator if there is no score for that service yet.

i can imagine the project benefiting from this approach and work that has already been done.
