### ISSUE TITLE
Case for 'Device fingerprinting' not found

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#461]
The case 'Device fingerprinting' https://github.com/tosdr/tosdr-build/blob/master/src/cases/device_fingerprinting.json does not seem to exist in the edit.tosdr.org database. maybe something went wrong with the import?

**Comment by JesseWeinstein** [comment]
I think https://edit.tosdr.org/cases/323 covers this, so this issue can probably be closed?

**Comment by michielbdejong** [comment]
yes, thanks!
