### ISSUE TITLE
Connection to 3rd parties

### ISSUE THREAD

**Issue by christalib** [tosdr/edit.tosdr.org#466]
From IRC: 

> btw, it is a bit sad to see that tosdr.org forces me to leak information to three other sites to get the editor to work: jquery cloudflare bootstrapcdn (discovered using umatrix).

he's speaking about edit (that's why it's on this repo)

**Comment by michielbdejong** [comment]
we could host our own copy of jquery and bootstrapcdn, but in our current setup it's not feasible to avoid leaking data to cloudflare and heroku, and also note that heroku is in its turn hosted on amazon IIRC.

it's a matter of priorities, we're focusing on tool development now, and heroku saves us a lot of time in our process.
