### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by christalib** [tosdr/edit.tosdr.org#467]
A list reminder of things we need to document.

Things we need to document:
* [ ] On tosdr.org, how to add a service (going to edit etc.)

**Comment by JesseWeinstein** [comment]
Is this still relevant?

**Comment by Vinnl** [comment]
I guess not.

**Comment by madoleary** [comment]
I think this is still super relevant. We don't have a lot of user documentation and always receive emails for how to navigate or get started on the site.
