### ISSUE TITLE
Proposal: new tosdr.org website

### ISSUE THREAD

**Issue by Vinnl** [tosdr/edit.tosdr.org#537]
I'd like to propose a rework of the current tosdr.org website with the following goals:

- Still be a static site to minimise the risk of downtime
- Prominently feature the blog, listing its latest blog posts
- Has installation of the browser add-ons as the primary call-to-action, preferably directly linking to the version appropriate for the user's browser
- No more inconsistency (for example, the current website features a link to our OpenCollective, but then https://tosdr.org/get-involved.html suddenly shows a Flattr button again)
- Allow the site to be built automatically, e.g. in response to publishing a new blog post in Ghost, or once a day with a new export of Phoenix data
- Nice to have: have the site be generated from API data, to make sure that we're eating our own dogfood. In other words, when people use our API, they are guaranteed to have access to the same data that we show on the website.

To facilitate discussing what this could look like, I've built a preliminary version of such a site at https://github.com/tosdr/tosdr-static, which is deployed on commits to `master` to http://vinnl.gitlab.io/tosdr-static, and which could [be triggered by a Ghost webhook](https://github.com/tosdr/tosdr-static/issues/1).

Note that that is just a prototype, and I'm fine with throwing out that code and building something else. The main goal is hearing what you think :)

/cc @madoleary @piks3l @michielbdejong

**Comment by Vinnl** [comment]
Some initial comments from Michiel after just discussing this in person:

- It would be nice if this would be written as part of Phoenix, so we have a single language for our codebase, and that you can check what the static website would look like live on Phoenix.
- It could also be generated directly from the database from ERB templates.
- There's probably a gem to export (part of) a website to a static template, and worst case we use `wget`.
- We could ask Jan to take a look at the design again, maybe do a hackathon in Berlin.

Anything else or anything I misrepresented @michielbdejong?

**Comment by piks3l** [comment]
Agreed, but let's run in through the designers of our team so we can make a beautiful one ! (sorry I'm a bit away this months, lots of work and not much time)

**Comment by madoleary** [comment]
So cool Vincent!

A few points:

1. I am 1,000% behind this idea.
2. No more cards on the main page? I'm kind of attached to them.
3. We have designers? lol
4. To write as part of Phoenix, we could modernize by finally having a Phoenix front in a JS framework that retrieves backend data through ajax requests. I would be very interested in helping with this, as to build my JS muscles, which are no longer atrophied thanks to my current work.
5. Agree about the API.
6. Can we please do a hackathon in Berlin?????!

**Comment by piks3l** [comment]
> No more cards on the main page? I'm kind of attached to them.

We still have the modals of the tosdr.org website which must stay as they are the most important part of the website.

> To write as part of Phoenix, we could modernize by finally having a Phoenix front in a JS framework that retrieves backend data through ajax requests. I would be very interested in helping with this, as to build my JS muscles, which are no longer atrophied thanks to my current work.

That seems to me a huge task. I don't think it's something we should do now as we agreed not to make new features and having the data and the processes 100% working. Because it will mean to replace the whole erb templates...

> Nice to have: have the site be generated from API data, to make sure that we're eating our own dogfood. In other words, when people use our API, they are guaranteed to have access to the same data that we show on the website.

Isn't that already the case for the data on tosdr.org ?

**Comment by madoleary** [comment]
For what it's worth, I don't think it really would be a huge task, since the application itself isn't that large. But point taken...

**Comment by piks3l** [comment]
> For what it's worth, I don't think it really would be a huge task, since the application itself isn't that large. But point taken...

I'm not against it, but I am not sure it's something we should do now...

**Comment by Vinnl** [comment]
> Agreed, but let's run in through the designers of our team so we can make a beautiful one ! (sorry I'm a bit away this months, lots of work and not much time)

Agreed, Michiel suggested this as well. Note that it's not so much the design I'm proposing, as well as making the add-on and blog more prominent. Which also means that 

> No more cards on the main page? I'm kind of attached to them.

cards could definitely come back, I didn't spend too much time on this layout :)

> To write as part of Phoenix, we could modernize by finally having a Phoenix front in a JS framework that retrieves backend data through ajax requests. I would be very interested in helping with this, as to build my JS muscles, which are no longer atrophied thanks to my current work.

I don't have a strong opinion either way (though I don't feel like I could contribute that much to writing this in Ruby), but you might want to look at the current code then :) It's not too complicated Javascript, except there's a bit of strange syntax in it (namely [JSX](https://reactjs.org/docs/introducing-jsx.html) and some TypeScript). Since it's generated from JSON that can be output by Phoenix, it's somewhat already functioning as a front-end with Phoenix as the API, it's just that it fetches the API data during build-time. And of course, it doesn't support editing points, but that's the idea :)

> We still have the modals of the tosdr.org website which must stay as they are the most important part of the website.

(I'm putting on a UX hat here, which is not my main expertise, so take it with a grain of salt.) Typically, modals are used for tasks that the user _needs_ to complete before being able to continue, and that needs their full attention (which is why everything outside the modal is made inaccessible). So I'm not quite sure whether modals are the best UX here.

Of course, the actual display of the points should stay - they are still there, just on a separate page. (And just three of them, since this is generated from mock data pending #523.)

> Isn't that already the case for the data on tosdr.org ?

I think (IIRC) that that is indeed already the case on current tosdr.org - I just think it's important that that remains the case :)
