### ISSUE TITLE
Only show the annotate link when we have documents on a service

### ISSUE THREAD

**Issue by Vinnl** [tosdr/edit.tosdr.org#541]
Not sure if this is easy to do, but it would be nice to have. Right now, you just end up on an empty page if there are no docs.

**Comment by JesseWeinstein** [comment]
I think this is already resolved, if we are talking about the link on the Services table.

**Comment by JesseWeinstein** [comment]
Although it would be better if this linked to the "Upload a document" page instead. I'll make a PR.

**Comment by Vinnl** [comment]
Agreed, and agreed.
