### ISSUE TITLE
grey out 'Crawl Document' button if document already has points

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#568]
otherwise it would be too destructive. crawl also happens on https://tosback.org and the result from that is imported by the `db/import_from_tosback2.rb` job. So crawling from the UI should only be allowed for newly added or updated documents, before annotation has started.

**Comment by JesseWeinstein** [comment]
We still need a way to handle updates to documents, if not crawling them again...

**Comment by Vinnl** [comment]
I think this issue is actually redundant now: when a document is recrawled, we now [try to find the new location of quotes](https://github.com/tosdr/edit.tosdr.org/blob/master/app/controllers/documents_controller.rb#L134). If they can't be found, the points are moved back to Draft status.
