### ISSUE TITLE
Only allow curators to mark service reviews as comprehensive

### ISSUE THREAD

**Issue by Vinnl** [tosdr/edit.tosdr.org#598]

**Comment by michielbdejong** [comment]
If we implement my proposal from #614 then only curators or the creator of that service will be able to do this. Do you think that's ok?

**Comment by Vinnl** [comment]
@michielbdejong Marking a service as comprehensively reviewed will cause it to be exported to the website. Since many people create reviews for their own services, it might be good to only allow curators to mark them as comprehensive. After all, a service owner would otherwise only have to get a single positive point to be approved to get an A rating.

That said, I don't think this is a high priority issue - this "misuse" has not occurred yet, and it can still be caught in the export.
