### ISSUE TITLE
problem crawling Meteor-generated site

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#650]
https://edit.tosdr.org/documents/330

In theory, phantomjs should just render this site the same way your browser does, executing the Meteor xhr logic. We could try a newer headless browser engine, if Heroku supports it.

**Comment by Vinnl** [comment]
> We could try a newer headless browser engine, if Heroku supports it.

That's probably a good idea, given that [phantomjs has been discontinued for a while](https://github.com/teamcapybara/capybara#poltergeist). The most future-proof solution would probably to use the [Selenium driver](https://github.com/teamcapybara/capybara#selenium), but I'm not sure what needs to be done to install Java+Selenium+Firefox/Chrome on Heroku. What did you have to do to install phantomjs back then?

**Comment by michielbdejong** [comment]
another interesting case is https://edit.tosdr.org/documents/338, where you get a maintenance warning if you select xpath `//main` but you get the correct content if you do not select an xpath.

We now have `heroku buildpacks:add https://github.com/stomita/heroku-buildpack-phantomjs`, we could probably use https://github.com/heroku/heroku-buildpack-chromedriver
