### ISSUE TITLE
Allow changing status to Pending when adding a comment to a changes-requested point?

### ISSUE THREAD

**Issue by Vinnl** [tosdr/edit.tosdr.org#707]
When a curator requests changes, it might not immediately be clear to a point's author what they have to do. In that case, they might leave a comment asking for clarification. However, if the point's status remains changes-requested, then the curator won't see those new comments. Thus, perhaps we should change it to Pending when a point's author adds a comment on a changes-requested point?

**Update:** As discussed below, the best solution would probably be to show a checkbox (e.g. "Request another review") when a point's author adds a comment to a point that's changes-requested.

**Comment by Vinnl** [comment]
Oh haha, the use case is different, but the solution the same I guess. Is there a case in which a point's author would like to add a comment, but keep the status changes-requested?

**Comment by michielbdejong** [comment]
it would be confusing if 'Add Comment' usually means 'Add Comment', but in this specific case where a) you are the author and b) the current status is changes-requested, the meaning of that same button changes to 'Add Comment and set back to Pending'?

Maybe what we could do is in the Add Comment view, if those two conditions are true, show a checkbox saying 'and set back to pending', but I would vote for setting that checkbox default unchecked. Or show two buttons, one for 'Add comment' and one for 'Resubmit'

**Comment by Vinnl** [comment]
Sounds good, I'll update the description.

**Comment by JesseWeinstein** [comment]
This may be already done?

**Comment by michielbdejong** [comment]
yes, i think it is! thanks.
