### ISSUE TITLE
Implement Kaminari for pagination?

### ISSUE THREAD

**Issue by madoleary** [tosdr/edit.tosdr.org#730]
Kaminari is a nice little gem that does pagination in Ruby apps: https://github.com/kaminari/kaminari

It's pretty straightforward, and we could implement it to paginate some of our larger tables, which I think would be a meaningful improvement in UX.

**Comment by michielbdejong** [comment]
i think they're truncated now at 50 rows - do you ever reach the bottom of the page and find you're longing to click a 'next' button? usually you would search the points and services tables, not browse them, right?

**Comment by madoleary** [comment]
Haha, "longing" is probably not the right word. But does search only query
the 50 that are there, or does it query everything? I think there's value
in giving users the option to browse, if they want, though.

**Comment by michielbdejong** [comment]
the limit is applied after the query. so it's basically the same as pagination, but pages 2 and further are not accessible
