### ISSUE TITLE
Why do 'topics' have a 'privacy_related?' property?

### ISSUE THREAD

**Issue by madoleary** [tosdr/edit.tosdr.org#740]
So many of them are not privacy-related, when they probably should be, for one. Two, cases also have a privacy-related property. What does the privacy-related property on topics do, that the privacy-related property on cases does not do?

**Comment by michielbdejong** [comment]
I wasn't aware that privacy_related existed on topics, I think we probably only want it on cases.

**Comment by michielbdejong** [comment]
Ah I guess that is because we introduced privacy_related before we implemented cases.

**Comment by michielbdejong** [comment]
I think probably we introduced privacy_related before we implemented cases, that's probably why they were initially slapped on to topics. But I think now the privacy_related flag should be on cases, not on topics.

**Comment by piks3l** [comment]
Privacy related was a tag we add for DDG to parse our data as they were only interested in those. If I recall the goal was to have them on topics. I'm not sure cases should have this attribute as they already belong to topics

**Comment by michielbdejong** [comment]
yeah, as long as we don't have it in two places :) we are currently exporting the flag on cases and ignoring the one on topics, but you can switch it around if you think that's better, and if you think the cases in one topic are always either all privacy related, or none of them are

**Comment by madoleary** [comment]
I think having it on cases is better, since cases represent the parts that make up topics, and therefore are more representative.

**Comment by madoleary** [comment]
just made a PR to address this
