### ISSUE TITLE
500 error when not logged in on https://edit.tosdr.org/cases

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#747]
```
ActionView::Template::Error (undefined method `curator?' for nil:NilClass):

**Comment by michielbdejong** [comment]
@madoleary i think this was introduced by your table view, see https://github.com/tosdr/edit.tosdr.org/blob/master/app/views/cases/index.html.erb#L20

maybe it  should  say  `<% if current_user&.curator? %>`?

**Comment by michielbdejong** [comment]
this might be happening in other places too, we  should  check

**Comment by michielbdejong** [comment]
true, but  that's never a reason for a 500 error :) i gave people that link

**Comment by madoleary** [comment]
My point is that are users supposed to see cases if they're not logged in?
They get redirected to the sign-up/log-in page for /points, /services,
/topics.

**Comment by madoleary** [comment]
See my latest comment

**Comment by michielbdejong** [comment]
yes, unless maybe if  we think the page is  too resource intensive. it's open data and not secret.

**Comment by madoleary** [comment]
Okay...so remove current_user policy from cases, but maintain the
redirection for points, services, topics?

**Comment by michielbdejong** [comment]
well, not remove the current_user policy altogether, because the check for moderator status on that line is correct.
we should just make sure it doesn't error when current_user is undefined.

**Comment by madoleary** [comment]
Okay. I can do a quick fix directly to master, if that's alright.

**Comment by madoleary** [comment]
It's fixed. Moving forward, we should consider whether non-registered users should be able to also see points, or services, or topics.

**Comment by madoleary** [comment]
Argh now I see on cases show that the delete button is available to
everyone. Will fix momentarily. A colleague is using my computer.

**Comment by madoleary** [comment]
all good now :)

**Comment by michielbdejong** [comment]
awesome, thanks for the superfast fix!
