### ISSUE TITLE
Implement some sort of throttling mechanism to prevent spam

### ISSUE THREAD

**Issue by madoleary** [tosdr/edit.tosdr.org#752]
This could include a captcha on forms, or an implementation of the gem rack-attack.

**Comment by madoleary** [comment]
If we go with the captcha, which models would require captchas on their forms?

**Comment by madoleary** [comment]
I'm not sure. Probably don't need it for sign-up. I was thinking yes for creation of points, but in a way that process is kind of already throttled via our review system. Still perhaps a good idea to add it to point-creation to prevent spamming of "pending" points.

**Comment by christalib** [comment]
Done in #760 and #759
