### ISSUE TITLE
Keep document layout

### ISSUE THREAD

**Issue by wedza** [tosdr/edit.tosdr.org#766]
Hello,

Because I was using TOSDR as a visitor for a long time, I decided to start contributing to the project. Sadly, I found the document annotating process pretty uneasy.

Most of privacy policies have been formatted, to be easier to read. However, when the document fetches, the document looses all his layout, keeping only HTML tags. 

I found that it is pretty difficult to read a document like this, without any formatting. So I'm actually reading the document on the original page, and then, when I want to annotate, search the same area on the "crawled" version of TOSDR.

I think this is a pretty difficult process for a collaboration-based platform, and it would be easier if the crawled document actually "renders" the HTML tags to keep the original formatting.

This definitely shouldn't be a top priority, but would definitely make the life of contributors easier.

Thanks for your amazing work , and making the web more clear.

![image](https://user-images.githubusercontent.com/20335741/51326181-d263ee80-1a6e-11e9-84cf-81c6df890e62.png)

**Comment by wedza** [comment]
Sorry, didn't notice that there were [already an issue about that](https://github.com/tosdr/edit.tosdr.org/issues/726).

Closing#766

**Comment by michielbdejong** [comment]
Thanks, you're absolutely right!
I remember it was quite tricky to get that view working, but we  should try to get at least newlines and maybe also font size shown in the original way.
