### ISSUE TITLE
"Url has already been taken" unclear error message

### ISSUE THREAD

**Issue by arthurlutz** [tosdr/edit.tosdr.org#772]
```
Url

has already been taken

Where should we fetch this document from
```

![screenshot from 2019-02-14 18-23-20](https://user-images.githubusercontent.com/108437/52804911-ae9fc280-3085-11e9-9ce4-6047ab89dfda.png)

Does this mean the document is already crawled somewhere ? if so, maybe a link to the existing document/service ?

**Comment by madoleary** [comment]
On which form are you seeing this? When you try to create a service?

**Comment by arthurlutz** [comment]
No, when I try to add a document

**Comment by madoleary** [comment]
I see! I'll take a look

**Comment by madoleary** [comment]
Yes, indeed this document has been added already. I'm working on something now to make this more obvious and helpful.

**Comment by madoleary** [comment]
Hello! I merged a branch this morning that should ameliorate this problem. If you want, test it out and let us know how it is. I'll keep the issue open.

**Comment by madoleary** [comment]
Gonna close this out since it seems to be working okay!
