### ISSUE TITLE
1052

### ISSUE THREAD

**Issue by pachamaltese** [tosdr/edit.tosdr.org#782]
this should be removed:
https://edit.tosdr.org/documents/1052

it shows md5sums and tons of stuff that is not part of ToS

**Comment by madoleary** [comment]
Hi! Are all of these inclusions a result of the scraper, @michielbdejong ?

**Comment by pachamaltese** [comment]
@JustinBack Hi! In the end, tradestatistics.io was never added to TOS;DR :(

**Comment by JustinBack** [comment]
Thats because all the links to the documents lead to a 404

https://docs.tradestatistics.io/datasets.html#code-of-conduct

nor does https://tradestatistics.io/#contributions work

**Comment by pachamaltese** [comment]
so sorry, I added OTS when I created it a few years ago
now the links are
https://docs.tradestatistics.io/index.html#code-of-conduct
https://docs.tradestatistics.io/index.html#contact

**Comment by JustinBack** [comment]
Thanks to the new crawler I was able to add the document

https://edit.tosdr.org/documents/1052

**Comment by JustinBack** [comment]
Correction: https://edit.tosdr.org/documents/1679
