### ISSUE TITLE
Bad xpath

### ISSUE THREAD

**Issue by clement-f** [tosdr/edit.tosdr.org#785]
This document should be removed:
https://edit.tosdr.org/documents/1068
The xpath is wrong so the document is empty.
I can't find a way to do it. It would be easier to have a "delete" or "edit" button.

**Comment by madoleary** [comment]
Hi! Just deleted it. Thanks for pointing it out. I agree that if you've created the document, you ought to have the rights to 'edit' and 'delete' it. Did you create this document? At the moment, only users with the status of 'curator' can edit and delete documents.

**Comment by clement-f** [comment]
Yes, I did create this document. Thanks for deleting my mistake.
