### ISSUE TITLE
Tosdr/edit.tosdr.org

### ISSUE THREAD

**Issue by allmfrd** [tosdr/edit.tosdr.org#787]
edit.tosdr.org will not recognize my email password for some reason I can't download it.And I can't secure my account.

**Comment by allmfrd** [comment]
What should I do now

**Comment by madoleary** [comment]
Hi! Were you able to create an account?

**Comment by allmfrd** [comment]
Hi I don't think so I'm kinda way over my head here lol.

**Comment by madoleary** [comment]
No problem. Did you try to create an account through this page: https://edit.tosdr.org/users/sign_up ? If so, what errors did you receive?

**Comment by allmfrd** [comment]
I keep trying but, for some reason my email says its deactivated or my password is changed. In being cyber stalked and its nerve racking.

**Comment by madoleary** [comment]
Ah. I'm not aware of this deactivation error or why it would occur. Would you be comfortable sharing the email that you're trying to sign up with? This way I can check out our database to see if your email is in there, or at least get a better sense of what's going wrong. You can send it to team@tosdr.org

**Comment by madoleary** [comment]
Received! I'll take a look this evening.

**Comment by madoleary** [comment]
Actually I just had a quick look. There is indeed one account with your email. It was created today (UTC time). It was also confirmed today, which means a confirmation email was sent to your email, and the confirmation link inside of that email was clicked. The account associated with this email is not deactivated. I would advise the following: 1) Try resetting the password, 2) If resetting the password doesn't work, I can manually delete the account, and you can try creating a new one from scratch.

**Comment by allmfrd** [comment]
Yeah....its not that easy I think whoever is behind the attacks wants the
account deleted. I actually sent feed back to google last year and they
confirmed someone with the email address nclcmpbll@gmail.com had
unauthorized access to my account. I could never find that confirmation
again. Its scary

**Comment by madoleary** [comment]
Okay, well if this is an issue of your email being maliciously targeted, it's somewhat outside of the scope of what I can help you with, with respect to joining edit.tosdr.org. You might consider setting up a new email.
