### ISSUE TITLE
 "Order Services By Rating" works only partially

### ISSUE THREAD

**Issue by JesseWeinstein** [tosdr/edit.tosdr.org#822]
It sorts the first few entries, but doesn't sort all of them. See #817 for the previous ticket on this.

**Comment by madoleary** [comment]
Hello! Good catches. It wasn't working because the sorting mechanism wasn't taking into account the "E" ratings. I deployed a fix for this problem, as well as the annoying issue with the table headers. Should be working now; it is for me.

**Comment by JesseWeinstein** [comment]
Yep, works for me, too! Thanks.
