### ISSUE TITLE
Disable Flattr

### ISSUE THREAD

**Issue by JesseWeinstein** [tosdr/edit.tosdr.org#840]
ToS;DR has a Flattr page, here: https://flattr.com/@tosdr -- but I heard from @Vinnl that it may not actually get money to the current team anymore? This ticket is intended to straighten that out, and either get it working again, or get it firmly shut down (and any references to it removed from the website).

**Comment by christalib** [comment]
Going to take care of that. It's a quickfix

**Comment by christalib** [comment]
Unless I am mistaken, there isn't any reference on the website anymore (I searched through the code of edit and the main website). Feel free to reopen the issue if I was wrong.
