### ISSUE TITLE
Points have a topic_id but it isn't used

### ISSUE THREAD

**Issue by JesseWeinstein** [tosdr/edit.tosdr.org#846]
I was hoping to list the count of pending points in each topic, and it looked like that would be easy because there was a direct link between topics and points -- but this link does not appear to actually be populated. We should either populate it or remove it.

**Comment by madoleary** [comment]
About half of the points in the production database have a topic_id and half don't. I imagine that this is due to us making the transition to cases and the annotate view. Right now, when points are made through the annotate view, only a case_id is set for the point, and cases belong to topics. I suppose we could remove the topic_id column on points, although I would be curious to hear the opinions of @Vinnl and @michielbdejong .

**Comment by Vinnl** [comment]
Another option might be to add a method to the points model that fetches its topic if it exists, and if not, fetches the topic of its linked case if there is one?

But yeah, i don't think we currently stimulate adding points to topics that much, so I'd be fine with removing it too. (But then, I don't care for topics too much in the first place, so don't attach too much weight to my opinion here.)

**Comment by madoleary** [comment]
I personally think it would be find to remove the association, since most
of what we do with respect to points centers around cases, and topics are
more or less just a way to organize cases.

**Comment by madoleary** [comment]
Also, to the extent that this is interesting to you guys, @JesseWeinstein and @Vinnl, during our meeting in Berlin we talked about getting rid of the topics index page (https://edit.tosdr.org/topics) altogether. This would be part of a broader effort to consolidate the number of views that we have. So I think what this means is that we would only have the cases index page (https://edit.tosdr.org/cases), where the cases are already sorted according to topic.

**Comment by madoleary** [comment]
Here's where we discussed it: https://codimd.indie.host/tosdr-weekend-issues#

**Comment by Vinnl** [comment]
That certainly has my blessing :)

**Comment by michielbdejong** [comment]
Yes, go ahead and remove the topic_id on Points, it should be derived from the case.
