### ISSUE TITLE
More efficient way to calculate ratings

### ISSUE THREAD

**Issue by JesseWeinstein** [tosdr/edit.tosdr.org#855]
(below originally written by @madoleary)

`@services = Service.includes(points: [:case]).all` needs to be added back for the time being. To get the rating for each service, we're making multiple calls to points and their case. See the "service_rating_get" method in the Service model. We've had discussions in the past about finding a more efficient way to calculate these ratings, so we're very open to suggestions, on that front. I've recently been thinking about having a rating column for services, and updating it via some type of cron task that runs once or twice a day, or more often, depending on how demanding it is for the servers.

There's no existing "rating" column for services. It only exists on case, which passes it to point. We tally the ratings of the points, then use that to calculate a type of balance, which determines the rating of the service.

**Comment by madoleary** [comment]
Marking this as resolved because now we've got a proper rating column on services and a cron task calculating it in the background.
