### ISSUE TITLE
Review Queue: filter by source language

### ISSUE THREAD

**Issue by drichardson** [tosdr/edit.tosdr.org#859]
This is a feature request to be able to filter review queues by language.

1. When the document crawl occurs, save the language (returned by either the HTTP Content-Language header or HTML lang attribute).
2. When editors sign up, they can specify a list of languages they read and then choose to see only reviews for languages in that list.

**Comment by drichardson** [comment]
To show how this would be helpful, my current queue consists of all German points. The problem is, I can't moderate these, but nor can I skip them since there's no way to see more points.

![image](https://user-images.githubusercontent.com/36176/65557516-849a6280-dee8-11e9-99f8-503d468d0e97.png)

**Comment by JesseWeinstein** [comment]
The queue isn't actually a very good way to find points to review; you can see the whole list by searching for "pending" on the Points page, like this: https://edit.tosdr.org/points?utf8=%E2%9C%93&query=pending&commit=Search (which shows we currently have 775 pending). For finding ones to review, I prefer to look at them by Cases, and work to review all the ones in particular cases, one after another.

**Comment by drichardson** [comment]
@JesseWeinstein I agree that working cases is a nice way to process stuff, since you don't have to context switch continuously.

Also, I'm reconsidering this request. I did a bunch of reviews today of foreign languages that were pretty easy because they were annotated well. The problem with other languages is when someone links to the page but doesn't call out the specific text with an annotation, but that doesn't happen often.

I actually think this issue should be closed, and we should just focus on good (as short as possible and relevant) annotations that are more easily machine translated.

**Comment by drichardson** [comment]
Also, I didn't know about the URL filters you pointed out. Thanks for the tip @JesseWeinstein .
