### ISSUE TITLE
Make pending count a link

### ISSUE THREAD

**Issue by drichardson** [tosdr/edit.tosdr.org#862]
Go to a case like [Tracking](https://edit.tosdr.org/topics/25). There is a list of pending counts.

This is a feature request to make each pending count a link to a list of pending issues for that case.

Currently, you have to go to the entire list of issues, not just pending, which is a real time waster when you're just trying to process pending issues.

**Comment by Vinnl** [comment]
Thanks, this makes sense and was easy to implement, and I happened to have some time, so I've created PR #863 to do this :)
