### ISSUE TITLE
Unable to crawl page

### ISSUE THREAD

**Issue by elliott-king** [tosdr/edit.tosdr.org#873]
I am trying to add a TOS document to the Rescue Time service. However, it cannot crawl the page. 

The url is: 
https://help.rescuetime.com/article/164-rescuetimes-terms-of-service
The (both FF and Chrome) XPATH is:
`//*[@id="fullArticle"]`

I went out and tried a few XPATH testing sites, and could not get it to work within them either. I also tried an already-parsed document (https://about.500px.com/terms/), and it worked fine. I assume it is an difference with the layout of the document, that the XPATH searcher cannot handle? Even if I simply make the XPATH `/html`, nothing is returned.

**Comment by Donnnno** [comment]
Hi, I had the same problem today while trying to crawl Nexus Mods with it's ToS and privacy policy.
They use the same XPATH as your site: `//*[@id="fullArticle"]`
The url: https://help.nexusmods.com/article/20-privacy-policy and https://help.nexusmods.com/article/18-terms-of-service

**Comment by JustinBack** [comment]
This should be resolved with the new crawler.

Reopen if it still is not fixed though
