### ISSUE TITLE
Possible Leaderboard of Contributions?

### ISSUE THREAD

**Issue by Peepo1** [tosdr/edit.tosdr.org#875]
If Tosdr had a leaderboard, I think it would encourage friendly competition to contribute that ultimately benefits the site. Points could be given for approved points, documents added, and services added. The amount of points given would depend on the difficulty of the task.

**Comment by ohreally** [comment]
For people who feel it's important to be number 1, this might be a motivation to check their additions less thoroughly before submitting them.

**Comment by Peepo1** [comment]
Very good point, I didn't think about that.
