### ISSUE TITLE
No way to add a service?

### ISSUE THREAD

**Issue by aleksejrs** [tosdr/edit.tosdr.org#901]

**Comment by Vinnl** [comment]
Hi @aleksejrs, it's not super obvious, but the button to add a new service appears after you search for it - we used to see many duplicate services entered, so this was an attempt to mitigate that.

**Comment by aleksejrs** [comment]
Apparently the button does not appear for me, although I found a different way to add a service.

**Comment by michielbdejong** [comment]
Hi @aleksejrs, I made you a curator on the site, so the button should appear now if there are no search results for the services you're searching for.
