### ISSUE TITLE
about page mentions A-F instead of A-E

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#902]
https://edit.tosdr.org/about#classification mentions A-F instead of A-E

**Comment by JustinBack** [comment]
Yes thats right though? At least thats what the wiki says about the academic grade system in the US

![](https://justinback.jbcdn.net/captures/firefox_w8KqJmtxIB.png)

https://github.com/tosdr/edit.tosdr.org/blob/12bc5794cb79049c12b51430e041c23a4a2a5f47/app/views/pages/about.html.erb#L55

> similar to a grade on a school assignment

**Comment by JustinBack** [comment]
Nevermind, saw that everywhere the rating is A-E. Will create a PR
