### ISSUE TITLE
make instructions around service wikipedia page clearer

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#904]
should be clearer that it's optional to add a link to the wikipedia page about the service, because not all services have a wikipedia page.

**Comment by jesusjavier1859** [comment]
[https://bazoocam.live/](https://bazoocam.live/)
[https://chatzy.xyz/](https://chatzy.xyz/)
[https://myprepaid-center.co/]([](https://myprepaid-center.co/))
