### ISSUE TITLE
500 Error trying to open service 2257

### ISSUE THREAD

**Issue by aleksejrs** [tosdr/edit.tosdr.org#906]
https://edit.tosdr.org/services/2257 500 Internal Server Error

**Comment by michielbdejong** [comment]
I think this affects all services that have comments. This is what it looks like on localhost, cc @madoleary:

![Screenshot 2020-06-22 11 34 03](https://user-images.githubusercontent.com/408412/85272339-57311400-b47c-11ea-9a9d-1fdc56bd8f22.png)

**Comment by michielbdejong** [comment]
Weird, because https://github.com/tosdr/edit.tosdr.org/pull/899/files#diff-87566b96d92fb16cb3acc5d448ff3903R4 does say a ServiceComment can have many spams

**Comment by madoleary** [comment]
Did you run rails:db migrate?

**Comment by michielbdejong** [comment]
yes, Current version: 20200517080230

**Comment by madoleary** [comment]
Okay, taking a look now to see if I can replicate.

**Comment by michielbdejong** [comment]
I temporarily disabled service comments in production, so we can re-enable them when it's fixed

**Comment by madoleary** [comment]
I found the problem. Just a typo. Will test further locally, then deploy.

**Comment by madoleary** [comment]
Fixed and in production.

**Comment by michielbdejong** [comment]
\o/ thanks a lot!
