### ISSUE TITLE
deal with documents that apply to multiple services

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#915]

**Comment by michielbdejong** [comment]
for instance services 158: Apple, 304: Apple iCloud, 757: Apple Media Services.
If all documents for two services coincide then the two services are identical and should be merged. Maybe we should always merge to the biggest service and just give 'Google' or 'Amazon' a review if there is at least one generic document that applies to all sub-services?

I know for instance Amazon has generic as well as e.g. Kindle-specific docs but it would be so much easier to just keep it as a single review rather than splinter it up

**Comment by jesusjavier1859** [comment]
[https://gmxloginmail.de/](https://gmxloginmail.de/)
[https://techpourpc.fr/whatsapp-pour-pc/](https://techpourpc.fr/whatsapp-pour-pc/)
[https://techpourpc.fr/uc-browser-pour-pc/](https://techpourpc.fr/uc-browser-pour-pc/)
[https://techpourpc.fr/temple-run-2-pour-pc/](https://techpourpc.fr/temple-run-2-pour-pc/)
[https://ometv.vip/](https://ometv.vip/)
[https://myvanilladebitcard.site/](https://myvanilladebitcard.site/)
