### ISSUE TITLE
From `select id, service_id, url from documents where url in (select distinct a.url from documents a inner join documents b on  a.url = b.url where a.id != b.id) order by url` it seems that a lot of duplicate documents happen within the same service. So let me try to clean that up first.

### ISSUE THREAD

**Issue by TmsSl** [tosdr/edit.tosdr.org#916]
From `select id, service_id, url from documents where url in (select distinct a.url from documents a inner join documents b on  a.url = b.url where a.id != b.id) order by url` it seems that a lot of duplicate documents happen within the same service. So let me try to clean that up first.

* [ ] prohibit adding a document with a duplicate URL
* [ ] merge documents within a service
* [ ] deal with documents that apply to multiple services? see #915 

_Originally posted by @michielbdejong in https://github.com/tosdr/edit.tosdr.org/issues/914#issuecomment-647441697_

**Comment by michielbdejong** [comment]
```sql
select a.id,a.url,a.name, b.id,b.url,b.name from services a inner join services b on a.url = b.url where a.id != b.id and a.id<b.id and a.status is NULL and b.status is NULL;

select a.id,b.id,a.status from documents a inner join documents b on a.url = b.url where a.id != b.id and a.xpath=b.xpath and a.service_id=b.service_id and a.id<b.id and a.status is NULL and b.status is NULL;
