### ISSUE TITLE
add point status for 'not found in latest version of document'

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#922]
when a document is crawled, and the quote of a point is no longer found, now, we convert such a point to draft, which is not very accurate.

**Comment by Phabbits** [comment]
I believe you closed this issue with your update on the [forum](https://forum.tosdr.org/t/crawling-errors-crawling-update/407/2?u=serph): "Indeed, there are two new point states, approved-not-found and pending-not-found, both mean that the quote of the point was not found in the latest version of the document."

**Comment by JustinBack** [comment]
Good catch! Closed.
