### ISSUE TITLE
remove rate limiting for curators

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#929]
if the logged-in user is a curator, we probably shouldn't need to rate limit them

**Comment by madoleary** [comment]
Leaving this here as a potential solution to explore : https://github.com/rack/rack-attack/issues/397

**Comment by michielbdejong** [comment]
Tried changing `req.ip` to `req.ip unless current_user.curator?` in each of the throttle rules in config/initializers/rack_attack.rb but `current_user` is not available there.

**Comment by michielbdejong** [comment]
As a work-around for now I'll temporarily loosen the update-document limit for everyone for now, because that's the one we will be hitting while reviewing old pending points and old doc crawls.
