### ISSUE TITLE
Privacy Policy lists "no cookies"

### ISSUE THREAD

**Issue by JustinBack** [tosdr/edit.tosdr.org#937]
Just noticed it today while approving points.

The Privacy Policy states that "we do not use cookies" which is wrong. Cookies are used by the login process.

![grafik](https://user-images.githubusercontent.com/40178814/97087797-f7669780-162c-11eb-99be-367928f422e4.png)

https://github.com/tosdr/edit.tosdr.org/blob/1282fd36dec112f7d9eeed44206e5dec7c1f72b2/app/views/pages/about.html.erb#L108

**Comment by madoleary** [comment]
I wonder what the right language would be. We use cookies to manage your session when you log in, but do not use cookies to track your activity elsewhere online. Something like this? Wonder what @michielbdejong and @hugoroy think

**Comment by michielbdejong** [comment]
yeah, go for it! we use cookies on edit.tosdr.org but not on tosdr.org. maybe that's where the confusion came from.

**Comment by DrKJeff16** [comment]
> I wonder what the right language would be. We use cookies to manage your session when you log in, but do not use cookies to track your activity elsewhere online. Something like this? Wonder what @michielbdejong and @hugoroy think

I'd say that in that case we should point out that we do use Cookies, but no tracking/analytics cookies at all. Our `First-Party Cookies`, as far as I'm concerned, exist for remembering a user's session, which won't limit a user's overall experience if declined. We could also provide, if possible, a list of cookies we use, but that's merely a suggention.

> yeah, go for it! we use cookies on edit.tosdr.org but not on tosdr.org. maybe that's where the confusion came from.

Although I believe Justin told us that the [beta site](https://beta.tosdr.org) will use Cookies for language preferences, just to bear in mind in the future. 🤔

**Comment by JustinBack** [comment]
> Although I believe @JustinBack told us that the beta site will use Cookies for language preferences, just to bear in mind in the future. 🤔

Correct 😉

**Comment by JustinBack** [comment]
With 8b900bf8879b8ed3a4a2a6bbabbeafa7d2ab540c this is resolved.
