### ISSUE TITLE
Cases Endpoint for the API

### ISSUE THREAD

**Issue by JustinBack** [tosdr/edit.tosdr.org#941]
I think we need an endpoint for the cases to pull via the API. Currently there is no way to check for case details (weight, classification)

**Comment by madoleary** [comment]
Hello there, the cases endpoint is live

**Comment by JustinBack** [comment]
Great, thanks!

**Comment by JustinBack** [comment]
The case API is missing the "weights" property which is sadly required for the new website

**Comment by madoleary** [comment]
Indeed. I'll handle this before the end of the week.

**Comment by madoleary** [comment]
Okay, it's in the API now under the attribute "score". In the database, we store the weight as "score".
