### ISSUE TITLE
paginate JSON at certain API endpoints

### ISSUE THREAD

**Issue by madoleary** [tosdr/edit.tosdr.org#944]
certain API endpoints return enormous responses, which should be paginated. the paginated responses should contain metadata about the total number of records and the total number of pages.

**Comment by madoleary** [comment]
@JustinBack I've implemented a solution for the `/points` endpoint on the branch `fix-api`

* if you request `/points`, you'll receive all of the objects as usual
* if you request `/points?page=1`, you'll receive a response containing an object labeled `points` with the first 100 points, plus an object labeled `meta`, containing `total_pages` and `total_records`, where `total_records` indicates the total number of point objects
* this `meta` object exists on each response page

If this meets your requirements, I can merge it to master.

**Comment by JustinBack** [comment]
Thats great! Like the way I thought about it :D

**Comment by madoleary** [comment]
Cool, I'll merge and deploy tomorrow morning, then maybe implement the same thing for services.

**Comment by madoleary** [comment]
I've implemented pagination for the services endpoint. I'll close this issue, now. Please do not hesitate to create new issues if you have other suggestions or find other bugs with the API.
