### ISSUE TITLE
Topics Page not public

### ISSUE THREAD

**Issue by DrKJeff16** [tosdr/edit.tosdr.org#950]
# The Issue
Recently it has been discovered (by pederdm000) that the [Topics section](https://edit.tosdr.org/topics) of Phoenix is only accessible when logged in. It should be open to the public, right?

## Evidence (in order)

![Topics-1](https://user-images.githubusercontent.com/72052712/100522184-928fe700-316e-11eb-9ff0-25a47193baea.jpg)

![Topics-2](https://user-images.githubusercontent.com/72052712/100522194-99b6f500-316e-11eb-9bd8-074c56b1d04c.jpg)

![Topics-3](https://user-images.githubusercontent.com/72052712/100522200-9de31280-316e-11eb-8d64-81d9605d7a68.jpg)

**Comment by madoleary** [comment]
you're right ! it's been fixed.
