### ISSUE TITLE
500 error on Service page

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#964]
See https://edit.tosdr.org/services/2399

**Comment by madoleary** [comment]
this is occurring because it's trying to call `user.bot?` when `user` is nil. i'll add a condition to check for this edge case, but otherwise, @JustinBack, how would you like to label nil users?

**Comment by madoleary** [comment]
to be specific, `user` is nil when it doesn't exist in the database.

**Comment by madoleary** [comment]
fixed in production

**Comment by JustinBack** [comment]
> 
> 
> this is occurring because it's trying to call `user.bot?` when `user` is nil. i'll add a condition to check for this edge case, but otherwise, @JustinBack, how would you like to label nil users?

Then just skip the label for null users, I haven't seen any checks for null users in the other code

**Comment by JustinBack** [comment]
Nvm that! 
![grafik](https://user-images.githubusercontent.com/40178814/102307702-4a8e0400-3f65-11eb-8570-5a6ba98cdd5f.png)

I see now that "someone" is a deleted user, so I have changed the behaviour of the username function. Thanks @madoleary for fixing the bug!

**Comment by JustinBack** [comment]
Added in https://github.com/tosdr/edit.tosdr.org/commit/ae1a03791636b1f4dd46c0100e40c038f8e92081
