### ISSUE TITLE
Automated Declining for Changes-Requested?

### ISSUE THREAD

**Issue by DrKJeff16** [tosdr/edit.tosdr.org#975]
# Why The Suggestion

As established, we have approved a [new policy](https://forum.tosdr.org/t/new-changes-requested-policy/221) for Phoenix, in which points that get marked with `Changes-Requested` will be deleted if they haven't been updated two months after said status is set.

# Is It Possible To Make It Automated?

Is it feasible to create a bot-related process that automatically declines points after the passing of 60 days? Would make things a lot easier for Reviewers and Curators, specially if also done retroactively...

**Comment by JustinBack** [comment]
This should be easily integrated with rake tasks and schedule them on heroku

**Comment by madoleary** [comment]
Hey guys, yes, this is totally feasible. I can try to take a look this week.
