### ISSUE TITLE
Typo in service name/domain/WP edit view

### ISSUE THREAD

**Issue by ArloJamesBarnes** [tosdr/edit.tosdr.org#976]
>This will be used to referrenced the Wikipedia link of the service.

should be

>This will be used to reference the Wikipedia link of the service.

**Comment by JustinBack** [comment]
https://github.com/tosdr/edit.tosdr.org/blob/b5a4c6285688d7fffc3feeaeba12789c1bff017c/app/views/services/_form.html.erb#L7

found here, shortcut for future bug fixing :-)
